# Perus AntiCheat Prefixes


# Basic prefixes
# %player% - Gets player name.
# %check% - Gets the check that was violated.
# %stats% - Grabs the math statistics of the check.
# %vl% - Grabs the violation of the check.
# %version% - Grabs the version of the anticheat.

# Special prefixes
# %main-command% - Grabs main command if hider is enabled.
# %notifications-alias% - Grabs notifications aliases from the command set in config.yml.
# %help-alias% - Grabs aliases from the command set in config.yml.
# %logs-alias% - Grabs logs aliases from the command set in config.yml.
# %totalvl% - Grabs the total violations logged in the system.

# Types of Logging
# FlatFile - Stores violations into a file.
# MySQL or MySQL Lite - Stores violations into a database.
# MongoDB - Stores violations into a database.
# Redis - Stores violations into a database.

perus:
  messages:
    # Violation notification message
    notifications: "&7[&5P&7] &6%player% &7has violated &3%check% &8(&bx%vl%&8) &e%stats%"
    # Help message
    help: "&5Perus-AntiCheat Commands\n
    /%main-command% Notifications(%notifications-alias%)\n
    /%main-command% Help(%help-alias%)\n
    /%main-command% Logs(%logs-alias%) <target>\n"
    # Logs message
    logs: "&7[&5P&7] &6%player% has violated a total of %totalvl% checks!\n"